### ISSUE TITLE
Replace or add an X icon instead of Twitter.

### ISSUE THREAD

**Issue by encvoy-dev** [kytta/shareon#142] opened 2024-12-25 08:59 UTC
Hi, I think it's time to replace the Twitter icon or just add an X. If you need help with SVG, I can provide it.

**Comment by kytta** [comment] 2024-12-25 11:06
Duplicate of #86 (but also #91, #92, #112, and #121). Please, always search the issue tracker first before opening new issues.

**Closed** 2024-12-25 11:06 UTC
Labels: duplicate
